name: Build and Deploy

on:
  push:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Beeper Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.CI_REGISTRY }}
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}

      - name: Docker Build
        run: make release-ingress-controller
        env:
          BASE_IMAGE: rancher/nginx:ingress-nginx-1.7.1-hardened1
          E2E_IMAGE: rancher/hardened-build-base:v1.20.5b2
          PLATFORMS: amd64
          REGISTRY: "${{ secrets.CI_REGISTRY }}"
